In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

total_sum = 0 
df = pd.read_csv('chunk0.csv')
df

review_id                 user_id             business_id  \
0     LG2ZaYiOgpr2DK_90pYjNw  V34qejxNsCbcgD8C0HVk-Q  HQl28KMwrEKHqhFrrDqVNQ   
1     6TdNDKywdbjoTkizeMce8A  UgMW8bLE0QMJDCkQ1Ax5Mg  IS4cv902ykd8wj1TR0N3-A   
2     ZayJ1zWyWgY9S_TRLT_y9Q  aq_ZxGHiri48TUXJlpRkCQ  Pthe4qk5xh4n-ef-9bvMSg   
3     z4BCgTkfNtCu4XY5Lp97ww  jOERvhmK6_lo_XGUBPws_w  Ws8V970-mQt2X9CwCuT5zw   
4     Tyx7AxYQfSRnBFUIXUJwFA  HJECayULRM-6xh2GCCvLiA  l-nL4BmhzpZjcavooO48PQ   
...                      ...                     ...                     ...   
4995  ow1rduGaLvahRMnSCDKhQQ  YXro7DYEzalWWD43Q1gkzg  RazK5AssZZ9l_W6h-bTkUw   
4996  8ea12SYotvdIAJ4U180RaA  C4-DtyZClKlyIi9_9xc5AA  8jHLEXfoy3Q9TdvJYvtWvg   
4997  HUMUAEKIjFfAzbYGhHDRng  LcCRMIDz1JgshpPGYfLDcA  m9I_bnvcXpNrwAx6oViZng   
4998  fICf_R2jdMwxB732m34Z6A  TyepNPbEnMCy1_IhsT0YAg  VrGI7_nRjXpn0415S3coGQ   
4999  OCdJEoEqaPeaPFRojeOp7g  ffknU3Jt63V2IkAmH_DpOA  t6ZIBNrQjvtwor8W-u3sUg   

      stars  useful  funny  cool  \
0         5       1      0     0   
1         4       0      0     0   
2         5       1      0     0   
3         4       3      0     1   
4         4       2      1     1   
...     ...     ...    ...   ...   
4995      5       4      0     1   
4996      4       0      0     0   
4997      3       0      0     0   
4998      5       1      0     1   
4999      3       1      1     1   

                                                   text                 date  
0     I love Deagan's. I do. I really do. The atmosp...  2015-12-05 03:18:11  
1     Oh happy day, finally have a Canes near my cas...  2017-01-14 21:56:57  
2     Really good place with simple decor, amazing f...  2015-11-05 23:11:05  
3     I have been here twice. Very nice and laid bac...  2009-10-13 04:16:41  
4     ORDER In (Delivery) Review\n\nI discovered thi...  2015-10-17 01:38:13  
...                                                 ...                  ...  
4995  Delicious Frozen Treats! My fiance decided to ...  2018-05-29 17:13:02  
4996  We usually visit this place about two to three...  2015-04-02 13:22:01  
4997  Service was extremely fast and the food was go...  2015-06-21 04:00:25  
4998  Second time to Thai Style Noodle House, and se...  2012-05-29 23:32:18  
4999  This should definitely be rounded up to 3.5 st...  2011-06-30 22:03:30  

[5000 rows x 9 columns]

In [2]:
features = ["stars", "text"]

def combine_features(row):
    return str(row["stars"]) + " " + row["text"]

for feature in features:
    df[feature] = df[feature].fillna('')
    
df["combined_features"] = df.apply(combine_features,axis=1)
df

review_id                 user_id             business_id  \
0     LG2ZaYiOgpr2DK_90pYjNw  V34qejxNsCbcgD8C0HVk-Q  HQl28KMwrEKHqhFrrDqVNQ   
1     6TdNDKywdbjoTkizeMce8A  UgMW8bLE0QMJDCkQ1Ax5Mg  IS4cv902ykd8wj1TR0N3-A   
2     ZayJ1zWyWgY9S_TRLT_y9Q  aq_ZxGHiri48TUXJlpRkCQ  Pthe4qk5xh4n-ef-9bvMSg   
3     z4BCgTkfNtCu4XY5Lp97ww  jOERvhmK6_lo_XGUBPws_w  Ws8V970-mQt2X9CwCuT5zw   
4     Tyx7AxYQfSRnBFUIXUJwFA  HJECayULRM-6xh2GCCvLiA  l-nL4BmhzpZjcavooO48PQ   
...                      ...                     ...                     ...   
4995  ow1rduGaLvahRMnSCDKhQQ  YXro7DYEzalWWD43Q1gkzg  RazK5AssZZ9l_W6h-bTkUw   
4996  8ea12SYotvdIAJ4U180RaA  C4-DtyZClKlyIi9_9xc5AA  8jHLEXfoy3Q9TdvJYvtWvg   
4997  HUMUAEKIjFfAzbYGhHDRng  LcCRMIDz1JgshpPGYfLDcA  m9I_bnvcXpNrwAx6oViZng   
4998  fICf_R2jdMwxB732m34Z6A  TyepNPbEnMCy1_IhsT0YAg  VrGI7_nRjXpn0415S3coGQ   
4999  OCdJEoEqaPeaPFRojeOp7g  ffknU3Jt63V2IkAmH_DpOA  t6ZIBNrQjvtwor8W-u3sUg   

      stars  useful  funny  cool  \
0         5       1      0     0   
1         4       0      0     0   
2         5       1      0     0   
3         4       3      0     1   
4         4       2      1     1   
...     ...     ...    ...   ...   
4995      5       4      0     1   
4996      4       0      0     0   
4997      3       0      0     0   
4998      5       1      0     1   
4999      3       1      1     1   

                                                   text                 date  \
0     I love Deagan's. I do. I really do. The atmosp...  2015-12-05 03:18:11   
1     Oh happy day, finally have a Canes near my cas...  2017-01-14 21:56:57   
2     Really good place with simple decor, amazing f...  2015-11-05 23:11:05   
3     I have been here twice. Very nice and laid bac...  2009-10-13 04:16:41   
4     ORDER In (Delivery) Review\n\nI discovered thi...  2015-10-17 01:38:13   
...                                                 ...                  ...   
4995  Delicious Frozen Treats! My fiance decided to ...  2018-05-29 17:13:02   
4996  We usually visit this place about two to three...  2015-04-02 13:22:01   
4997  Service was extremely fast and the food was go...  2015-06-21 04:00:25   
4998  Second time to Thai Style Noodle House, and se...  2012-05-29 23:32:18   
4999  This should definitely be rounded up to 3.5 st...  2011-06-30 22:03:30   

                                      combined_features  
0     5 I love Deagan's. I do. I really do. The atmo...  
1     4 Oh happy day, finally have a Canes near my c...  
2     5 Really good place with simple decor, amazing...  
3     4 I have been here twice. Very nice and laid b...  
4     4 ORDER In (Delivery) Review\n\nI discovered t...  
...                                                 ...  
4995  5 Delicious Frozen Treats! My fiance decided t...  
4996  4 We usually visit this place about two to thr...  
4997  3 Service was extremely fast and the food was ...  
4998  5 Second time to Thai Style Noodle House, and ...  
4999  3 This should definitely be rounded up to 3.5 ...  

[5000 rows x 10 columns]

In [22]:
cv = CountVectorizer() 
count_matrix = cv.fit_transform(df["combined_features"])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)
print(cosine_sim.shape)

[[1.         0.50172355 0.44106393 ... 0.37536354 0.36592943 0.5203059 ]
 [0.50172355 1.         0.4272414  ... 0.4175     0.36538462 0.43333333]
 [0.44106393 0.4272414  1.         ... 0.35010059 0.31951814 0.40350576]
 ...
 [0.37536354 0.4175     0.35010059 ... 1.         0.29230769 0.34333333]
 [0.36592943 0.36538462 0.31951814 ... 0.29230769 1.         0.41538462]
 [0.5203059  0.43333333 0.40350576 ... 0.34333333 0.41538462 1.        ]]
(5000, 5000)


In [13]:
def get_text_from_UID(user_id):
    return df[df.user_id == user_id]["text"].values[0]
def get_BID_from_index(index):
    return df['business_id'][index]
def xget_index_from_BID(business_id):
    return df[df['business_id'] == business_id].index[0]

In [14]:
# get_BID_from_index(2)
# print (get_BID_from_index(2))
# get_index_from_BID("Pthe4qk5xh4n-ef-9bvMSg")

Pthe4qk5xh4n-ef-9bvMSg


2

In [6]:
BID_user_likes = "Pthe4qk5xh4n-ef-9bvMSg"
review_index = get_index_from_BID(BID_user_likes)
similar_res = list(enumerate(cosine_sim[review_index]))

In [10]:
sorted_similar_res = sorted(similar_res,key=lambda x:x[1],reverse=True)[1:6]
sorted_similar_res

[(4195, 0.5574000406292281),
 (586, 0.5571102159853991),
 (1363, 0.5446479475608366),
 (2175, 0.5427156169680769),
 (688, 0.5409310823772336)]

In [16]:
i=0
print("Top 5 similar resturant are:\n")
for element in sorted_similar_res:
    print(get_BID_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar resturant are:

0CElIQnJdQYF2bmsAiWczg
0VjHFdczi6Nln_nn8bucJQ
HzvCskRg2IdWFfBcEY5Ryw
_4Gpn_NIM94D9OFucgfaJQ
68PJJkcq_i0SlLqO6t7Qxw
